//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.Orchestrator.Extensions.SecureStores.HashicorpVault.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.Orchestrator.Extensions.SecureStores.HashicorpVault.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashicorp Vault json is invalid or is missing..
        /// </summary>
        internal static string HashicorpVaultJsonInvalidOrMissing {
            get {
                return ResourceManager.GetString("HashicorpVaultJsonInvalidOrMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashicorp Vault setting {0} is invalid or is missing..
        /// </summary>
        internal static string HashicorpVaultSettingInvalidOrMissing {
            get {
                return ResourceManager.GetString("HashicorpVaultSettingInvalidOrMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure store credentials are invalid..
        /// </summary>
        internal static string InvalidSecureStoreCredentials {
            get {
                return ResourceManager.GetString("InvalidSecureStoreCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null or empty secret name.
        /// </summary>
        internal static string InvalidSecureStoreSecretName {
            get {
                return ResourceManager.GetString("InvalidSecureStoreSecretName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure store operation {0} is not authorized..
        /// </summary>
        internal static string SecureStoreOperationNotAuthorizeded {
            get {
                return ResourceManager.GetString("SecureStoreOperationNotAuthorizeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret not found..
        /// </summary>
        internal static string SecureStoreSecretNotFound {
            get {
                return ResourceManager.GetString("SecureStoreSecretNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Type.
        /// </summary>
        internal static string SettingAuthenticationType {
            get {
                return ResourceManager.GetString("SettingAuthenticationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        internal static string SettingCertificate {
            get {
                return ResourceManager.GetString("SettingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Password.
        /// </summary>
        internal static string SettingCertificatePassword {
            get {
                return ResourceManager.GetString("SettingCertificatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Path.
        /// </summary>
        internal static string SettingDataPath {
            get {
                return ResourceManager.GetString("SettingDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        internal static string SettingNamespace {
            get {
                return ResourceManager.GetString("SettingNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SettingPassword {
            get {
                return ResourceManager.GetString("SettingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Id.
        /// </summary>
        internal static string SettingRoleId {
            get {
                return ResourceManager.GetString("SettingRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Id.
        /// </summary>
        internal static string SettingSecretId {
            get {
                return ResourceManager.GetString("SettingSecretId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secrets Engine.
        /// </summary>
        internal static string SettingSecretsEngine {
            get {
                return ResourceManager.GetString("SettingSecretsEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secrets Engine DataPath.
        /// </summary>
        internal static string SettingSecretsEnginePath {
            get {
                return ResourceManager.GetString("SettingSecretsEnginePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        internal static string SettingToken {
            get {
                return ResourceManager.GetString("SettingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string SettingUsername {
            get {
                return ResourceManager.GetString("SettingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault Uri.
        /// </summary>
        internal static string SettingVaultUri {
            get {
                return ResourceManager.GetString("SettingVaultUri", resourceCulture);
            }
        }
    }
}
